- name: Build AppImage
  uses: Kidev/qt-appimage@v1
  with:
    install_folder: './install'   # Required: Path to folder where Qt installed your project
    app_name: 'MyApp'             # Optional: App name (deduced from binary if not set)
    comment: 'My awesome Qt app'  # Optional: Desktop entry comment
    category: 'Graphics'          # Optional: Desktop category (default: Utility)
    icon: 'path/to/icon.png'      # Optional: Path to icon file
    binary: 'myapp'               # Optional: Binary name (auto-detected if not set)