# 文件路径：.github/workflows/windows-mingw.yml

name: Windows MinGW Qt Build & Release

on:
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/windows-mingw.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/windows-mingw.yml'

jobs:
  build:
    name: Build Qt Project with MinGW
    runs-on: windows-2022

    strategy:
      matrix:
        include:
          - qt_arch: win64_mingw73
            qt_ver: 5.14.2
            qt_tools: tools_mingw
            qt_tools_mingw_install: mingw730_6

    env:
      targetName: HelloActions-Qt.exe  # 最终生成的可执行文件名

    steps:
      # 1. 拉取源码
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # 2. 安装 Qt 工具链
      - name: Install Qt ${{ matrix.qt_ver }} with MinGW
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          aqtversion: '==3.1.*'
          arch: ${{ matrix.qt_arch }}
          tools: ${{ matrix.qt_tools }}
          host: windows
          target: desktop

      # 3. 配置 Qt5 环境变量
      - name: Configure Qt 5 environment variables
        if: startsWith(matrix.qt_ver, '5')
        shell: pwsh
        run: |
          Write-Output "${{ env.Qt5_DIR }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          Write-Output "${{ env.Qt5_DIR }}/../../Tools/${{ matrix.qt_tools_mingw_install }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # 4. 显示工具路径（用于调试）
      - name: Show qmake and mingw32-make path
        shell: pwsh
        run: |
          Get-Command qmake | Format-List
          Get-Command mingw32-make | Format-List

      # 5. 使用 qmake + mingw32-make 编译
      - name: Build with qmake and mingw32-make
        shell: cmd
        run: |
          qmake
          mingw32-make

      # 6. 打包产物（内联 PowerShell 脚本）
      - name: Package build output
        id: package
        env:
          archiveName: ${{ matrix.qt_ver }}-${{ matrix.qt_arch }}
          targetName: ${{ env.targetName }}
        shell: pwsh
        run: |
          # 删除旧目录
          if (Test-Path $env:archiveName) {
            Remove-Item -Recurse -Force $env:archiveName
          }

          # 创建新目录
          New-Item -ItemType Directory -Path $env:archiveName | Out-Null

          # 拷贝构建的 .exe 文件
          Copy-Item -Path "bin\release\$env:targetName" -Destination "$env:archiveName"

          # 调用 windeployqt 复制依赖
          windeployqt --qmldir . --plugindir "$env:archiveName\plugins" --no-translations --compiler-runtime "$env:archiveName\$env:targetName"

          # 删除不必要文件
          $excludeList = @("*.qmlc", "*.ilk", "*.exp", "*.lib", "*.pdb")
          foreach ($pattern in $excludeList) {
            Get-ChildItem -Path $env:archiveName -Recurse -Include $pattern | Remove-Item -Force
          }

          # 压缩为 zip 包
          Compress-Archive -Path "$env:archiveName" -DestinationPath "$env:archiveName.zip"

          # 输出变量供后续步骤引用
          "packageName=$($env:archiveName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          

      # 7. 上传打包后的 zip 文件
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ${{ steps.package.outputs.packageName }}.zip

      # 8. 若为 tag 推送，则创建 Release 并上传 zip
      - name: Create GitHub Release and upload artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}           # 自己创建的 PAT Token
          file: ${{ steps.package.outputs.packageName }}.zip
          asset_name: ${{ steps.package.outputs.packageName }}.zip
          tag: ${{ github.ref_name }}                     # 纯标签名
          overwrite: true

