name: Static Qt Build (MinGW 7.3.0)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install 7-Zip
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install 7zip

    - name: Download static Qt build
      run: |
        curl -L -o qt-static.zip https://github.com/youruser/yourrepo/releases/download/qt-static/qt-5.14.2-static-mingw730.zip
        7z x qt-static.zip -oQtStatic
        echo "QT_STATIC_PATH=$env:GITHUB_WORKSPACE\QtStatic" >> $env:GITHUB_ENV

    - name: Add Qt tools and MinGW 7.3.0 to PATH
      run: |
        echo "$env:QT_STATIC_PATH\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        echo "C:\mingw730\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Build Qt project statically
      run: |
        qmake CONFIG+=static CONFIG+=release
        mingw32-make -j4

    - name: Prepare release folder
      run: |
        mkdir release
        copy release\*.exe release\

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: main-latest
        name: "Auto Release (Static Build)"
        files: release/*.exe
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
