name: Build and Release

# Will trigger when a commit is tagged 'v*' (v1.0.0 for example)
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build, package, release
    runs-on: ubuntu-24.04
    steps:
      # Checkout your repo
      - uses: actions/checkout@v4

      # Install Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.2.1
        with:
          version: '6.8.3'

      # Build and install your project
      - name: Build project
        run: |
         cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(readlink -f ./install)
         cmake --build build
         cmake --install build

      # Package into .AppImage
      - name: Create AppImage
        id: appimage
        uses: Kidev/qt-appimage@v1
        with:
          install_folder: './install'
          app_name: 'MyApplication'
          comment: 'An awesome Qt application'
          category: 'Graphics'
          icon: './icon.png'
          binary: 'myapp'

      # Extract version from the commit tag
      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # Create release and upload AppImage
      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.appimage.outputs.appimage }}
          name: MyApplication ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}