name: Build and Release on Push

on:
  push:
    branches:
      - master       # 你可以改成你使用的分支，比如 master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Qt 5.14.2 (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.14.2'
        arch: 'win64_mingw81'
        modules: 'qttools qtwidgets'

    - name: Build with qmake + mingw32-make
      run: |
        qmake
        mingw32-make

    - name: Prepare release folder
      run: |
        mkdir release
        copy release\*.exe release\

    - name: Upload release artifact to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: main-latest               # 使用固定 tag，防止堆积多个 release
        name: "Auto Release from Main"
        files: release/*.exe
        draft: false
        prerelease: true                    # 设为预发布
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
